import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LeagueProvider } from "@/lib/league-context";
import { LayoutWrapper } from "@/components/topbar/LayoutWrapper";
import { getSupabaseServerClient } from "@/lib/supabase/client";
import type { LeagueSummary } from "@/lib/api/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getActiveLeague(): Promise<LeagueSummary | null> {
  try {
    const supabase = await getSupabaseServerClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return null;
    }

    const userResult = await supabase
      .from("users")
      .select("id, email, full_name, avatar_url, avatar_color, created_at, active_league_id")
      .eq("id", user.id)
      .single();

    if (userResult.error) {
      console.error("[layout] Error fetching user:", userResult.error.message);
      return null;
    }

    const userData = userResult.data;
    let effectiveLeagueId: string | null = null;

    if (userData.active_league_id) {
      const membershipCheck = await supabase
        .from("league_members")
        .select("user_id")
        .eq("user_id", user.id)
        .eq("league_id", userData.active_league_id)
        .single();

      if (!membershipCheck.error) {
        effectiveLeagueId = userData.active_league_id;
      }
    }

    if (!effectiveLeagueId) {
      const fallbackResult = await supabase
        .from("league_members")
        .select("league_id")
        .eq("user_id", user.id)
        .order("joined_at", { ascending: true })
        .limit(1)
        .single();

      if (fallbackResult.error) {
        console.error("[layout] Error fetching fallback league:", fallbackResult.error.message);
        return null;
      }

      effectiveLeagueId = fallbackResult.data.league_id;
    }

    const [leagueResult, memberResult] = await Promise.all([
      supabase
        .from("leagues")
        .select("id, name, access_type, logo_url, member_count")
        .eq("id", effectiveLeagueId)
        .single(),
      supabase
        .from("league_members")
        .select("role")
        .eq("user_id", user.id)
        .eq("league_id", effectiveLeagueId)
        .single(),
    ]);

    if (leagueResult.error || memberResult.error) {
      const err = leagueResult.error ?? memberResult.error;
      console.error("[layout] Database error:", err?.message);
      return null;
    }

    return {
      ...leagueResult.data,
      role: memberResult.data.role,
    };
  } catch (err) {
    console.error("[layout] Error in getActiveLeague:", err instanceof Error ? err.message : "unknown");
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const activeLeague = await getActiveLeague();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {activeLeague ? (
          <LeagueProvider initialLeague={activeLeague}>
            <LayoutWrapper>{children}</LayoutWrapper>
          </LeagueProvider>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
