import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LeagueProvider } from "@/lib/league-context";
import { LayoutWrapper } from "@/components/topbar/LayoutWrapper";
import { getSupabaseServerClient } from "@/lib/supabase/client";
import { getCachedActiveLeague } from "@/lib/leagues/get-active-league";
import type { LeagueSummary } from "@/lib/api/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// O root layout lê cookies (auth) em toda rota via getActiveLeague, então todas
// as páginas são dinâmicas de qualquer forma. Manter force-dynamic evita o Next
// tentar (e falhar) pré-renderizar estaticamente no build. O custo por request
// não vem daqui, e sim das queries — agora cacheadas em getCachedActiveLeague.
export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getActiveLeague(): Promise<LeagueSummary | null> {
  try {
    // Só o getUser roda por request (valida o cookie de sessão e nos dá o id).
    // As queries de liga/membership são cacheadas por userId em
    // getCachedActiveLeague — antes eram até 4 queries por navegação/prefetch,
    // a maior fonte de Active CPU restante na Vercel Fluid.
    const supabase = await getSupabaseServerClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return null;
    }

    return await getCachedActiveLeague(user.id);
  } catch (err) {
    console.error("[layout] Error in getActiveLeague:", err instanceof Error ? err.message : "unknown");
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const activeLeague = await getActiveLeague();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {activeLeague ? (
          <LeagueProvider initialLeague={activeLeague}>
            <LayoutWrapper>{children}</LayoutWrapper>
          </LeagueProvider>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
